Makefile
There was a space before the -i option which works on MACOSX buit causes the linux build to fail.
Remove the space.
Closes #11
=> Remove space in sed command for linux/macos compatibility

pkg/cache/application.go
Add the missing user and tags infor to the event to add a recovered application to the scheduler core.
=> Add user and tag to shim application request for recovery

Makefile, pkg/cache/context.go, pkg/cache/context_test.go, pkg/cache/task.go, pkg/common/events/recorder.go, pkg/common/events/recorder_test.go, pkg/conf/schedulerconf.go, pkg/plugin/predicates/predicator_test.go, pkg/plugin/predicates/predictor.go, pkg/shim/scheduler_mock.go
This patch contains the following changes
- Add pkg/common/events/recorder.go, it returns a global event recorder in singleton
- Publish events in multiple places, including
`context.go` -> when nodes are accepted or deleted from the scheduler
`task.go` -> when task is submitted/allocated/rejected/bound/bindFailed/completed
`predicator.go` -> when a task is unable to be allocated due to unsatisfactory of predicates
- Add TestMode in configs, in order to avoid initiating event recorder in tests (it will panic because this requires a workable kube-client)
- Minor improvement to schedulerconf.go, change interval type from `int` to `time.Duration`
=> expose scheduler events to K8s event system

pkg/cache/application.go, pkg/cache/node.go, pkg/cache/task.go, pkg/shim/scheduler.go
This fixes issue #31 
Transparently handle a no transition event as a success
=> Handle "no transistion" error from state machine as a success and noop

Makefile, deployments/admission-controllers/schedulername-mutation/README.md, deployments/admission-controllers/schedulername-mutation/admission_util.sh, deployments/admission-controllers/schedulername-mutation/configs.properties, deployments/admission-controllers/schedulername-mutation/generate-signed-ca.sh, deployments/admission-controllers/schedulername-mutation/server.yaml.template, deployments/image/admission/Dockerfile, pkg/plugin/admissioncontrollers/webhook/mutating_controller.go, pkg/plugin/admissioncontrollers/webhook/webhook.go
This PR adds a `mutating` admission controller, it watches all pod creation operations, and automatically add `schedulerName=yunikorn` to the pod spec before admitting it to the validation phase.
=> Add admission controller to mutate schedulerName on-the-fly

pkg/cache/context.go, pkg/cache/task.go, pkg/shim/scheduler.go, pkg/shim/scheduler_mock.go, pkg/shim/scheduler_test.go
this fixes #29 
Here is what happens, when the shim failed to bind a pod to the specified node, we marked the task as failed. However, we are not asking scheduler-core to release these allocations, this is causing the issue seeing in #29. So this PR contains the following changes
- make sure containers are released on failures
- added test case to cover this scenario
- minor improvements to the logs
=> make sure containers are released when on task failures

pkg/conf/schedulerconf.go, pkg/conf/schedulerconf_test.go, pkg/dispatcher/dispatcher.go, pkg/dispatcher/dispatcher_test.go
Currently when event channel in dispatcher is full, events could be lost and an error like "failed to dispatch event, event channel is full or closed" can be found in the scheduler log.
To solve this problem, I suppose that new event should wait in Dispatcher#dispatch until it's enqueued into the channel, add a new test case for this scenario as well.
=> Dispatcher events could be lost when event channel is full

Makefile, deployments/admission-controllers/schedulername-mutation/admission_util.sh, deployments/image/configmap/Dockerfile, helm-charts/yunikorn/templates/deployment.yaml, helm-charts/yunikorn/values.yaml, pkg/plugin/admissioncontrollers/webhook/mutating_controller.go
This patch is to simplify the deployment of the admission controller. Before this patch, we need to manually deploy the admission controller after scheduler is installed. After patch, all can be done by helm chart. And this patch does following:
- Pack the init scripts (generating certs, secrets etc) into the scheduler docker image
- In helm chart, added a property: `embedAdmissionController`, if true, the admission controller init hook will be triggered during the deployment of the scheduler, as a `postStart` hook.
- When we delete scheduler resources, it automatically deletes resources of the admission controller, including web-server, secrets, deployment, and service. This is done via `preStop` hook.
- If `embedAdmissionController` is false, no admission controller will be installed …
=> embedded admission controller into helm chart deployment

deployments/admission-controllers/schedulername-mutation/admission_util.sh
During the test, I found when deploying the scheduler + admission controller using the helm chart. The webhook server log prints some "TLS handshake error". This was because of the `caBundle` value set for the webserver was missing. Kubectl is not able to retrieve cluster context using in cluster configuration (running inside of the pod). The fix is to change a way of retrieving the ca.
The fix works for both helm chart and local deployment.
=> Fix the caBundle issue in the admission controller in helm chart

deployments/examples/admission-controller-tests/nginx-yk.yaml, deployments/examples/admission-controller-tests/nginx.yaml, helm-charts/yunikorn/values.yaml
This PR contains 2 changes
1. use a simpler config for default deployment, that has placement rule enabled, no need to set queues explicitly.
2. add some sample yamls for admission-controller tests
=> simplify the deployment and add some sample yaml

Makefile
earlier we were using "scheduler-admission-controller" 
now renamed to "yunikorn-scheduler-admission-controller"
=> change admission controller image name to match yunikorn standard

pkg/cache/application.go, pkg/cache/context_recovery.go, pkg/cache/context_recovery_test.go, pkg/shim/scheduler_test.go
After restarting scheduler with a running application which can be seen by the scheduler,  I found the recovery process is endless and always wait for the application whose state is Running. 
According to the code in Context#waitForAppRecovery, the condition to finish this recovery is that app state should be Accepted, but app state may also have a chance to be transitioned to Running and other states(like Completed, Killed, etc.) here.
Perhaps we can expect that recovery process of this app is finished when app state is not New and not Recovering?
@yangwwei @wilfred-s  please help to review this PR, thanks.
=> Fix endless recovery problem

pkg/conf/schedulerconf.go
There are lots of invocations to k8s such as evaluating predicates for new allocations or assuming/binding volumes for pods, what we can see now are only final error messages.
This PR proposes to show internal logs in these invocations via enabling klog and set its log level verbosity to 4 (represents debug level) when log level of YK is debug.
For example, we can see more details in the failed invocation of volumeBinder#BindPodVolumes as follows,  also can find the cause of the error is empty node according to this message:
```
I1218 03:20:41.571713       1 scheduler_binder.go:344] BindPodVolumes for pod "blink/job-e896ad2d-ee9e-437b-8e6f-jobmanager-taskmanager-2", node ""
```
And we can see below messages after successfully bound pod volumes:
```
I1219 03:26:25.144935       1 …
```
=> Support showing k8s logs in debug mode for better troubleshooting

pkg/cache/application_test.go, pkg/common/constants.go, pkg/dispatcher/dispatcher.go, pkg/dispatcher/dispatcher_test.go
Native spark on K8s adds a label "spark-app-selector" to track spark app ID. We should directly read from this label.
=> Identify spark pod with label spark-app-selector

go.mod, go.sum, pkg/cache/nodes_test.go, pkg/common/node_test.go, pkg/common/resource.go, pkg/common/resource_test.go
Kubelet can reserve some resources from scheduling, we should respect that. Otherwise, we might be running into race-conditions. Ie. yunikorn thinks there is enough resources on the node, but actually there isn't.
=> [YUNIKORN-32] YuniKorn should respect reserved resources on Kubelet.

Makefile
The target split in get-revision commands for yunikorn-core-revision and yunikorn-scheduler-interface-revision should be updated when the project names have changed from "yunikorn-xxx" to "incubator-yunikorn-xxx".
=> [YUNIKORN-82] Fix wrong revision in docker image.

pkg/cache/context_recovery.go, pkg/cache/context_recovery_test.go, pkg/common/events/states.go
In recovery phase, scheduler keeps waiting until all nodes are recovered, but not all nodes are considered according to Context#recover in context_recovery.go, only nodes with Healthy or Draining state will be counted, nodes with Rejected state should be counted as well.
Updates:
- nodes with Rejected state are counted
- Improve UT TestNodesRecovery
- Remove unused node state: Unhealthy
@yangwwei @wilfred-s  please help to review this PR. Thanks.
=> [YUNIKORN-84] Always waiting in recovery phase as long as rejected node exists

pkg/cache/application.go
Implementation detail:
- We now emit `FailedScheduling` event for all the erros that `task.sanityCheckBeforeScheduling()` returns. By checking both the yunikorn and the k8s code, the are exclusive list of cases:
- the `PersistentVolumeClaimNamespaceLister` 's internal data structure throws an error (k8s internal error)
- the `PersistentVolumeClaimNamespaceLister` from k8s API does not find the PVC in the data structure where it stores (this case)
- the PVC is being deleted (caught by YuniKorn)
- (any panic on the stack)
Tested on docker-desktop k8s cluster with the a pod with non-existing PVC. Typing `kubectl describe pod` results the following:
```
Events:
Type     Reason            Age                    From      Message
----     ------            ----                   ---- …
```
=> [YUNIKORN-95] YuniKorn does not emit FailedScheduling event to k8s if pod uses non-existing PVC

deployments/admission-controllers/scheduler/templates/server.yaml.template
When running on EKS, with custom network plugin enabled (e.g calico). Without using hostNetwork, the API server will not be able to connect to the webhook.
=> [YUNIKORN-121] The admission controller should use hostNetwork

.gitignore
Add `coverage.txt` to `.gitignore` .
=> [YUNIKORN-166] travis build change leaves code coverage file in the root

Makefile, deployments/admission-controllers/scheduler/templates/server.yaml.template, deployments/image/configmap/Dockerfile
Fix the hardcoded value and make sure the version is always aligned
=> YUNIKORN-158. Admission controller deployment file should use the same image version as the scheduler

pkg/cache/external/scheduler_cache.go, pkg/cache/external/scheduler_cache_test.go, pkg/cache/nodes.go, pkg/cache/nodes_test.go, pkg/common/test/schedulerapi_mock.go
Some times we found the scheduler state is being inconsistent with K8s. Looks like some addNode was not sent by the informer. In such case, we should make sure the node can be added as well via updateNode event.
=> [YUNIKORN-220] Some nodes might be missing if the addNode event is missing

go.mod, go.sum, pkg/cache/external/scheduler_cache.go
This is a false alarm, we do not need to throw an error when node is not found while removing a pod, just like: https://github.com/kubernetes/kubernetes/blob/2402bfd4bc329ae755250f5214351b1408a48eab/pkg/scheduler/internal/cache/cache.go#L446.
This is just like what commented here:
```
// Removes a pod from the cached node info. When a node is removed, some pod
// deletion events might arrive later. This is not a problem, as the pods in
// the node are assumed to be removed already.
```
=> [YUNIKORN-224] False alarm in the log while removing a pod from scheduler cache

pkg/cache/application.go, pkg/cache/application_test.go, pkg/cache/context.go, pkg/cache/context_test.go, pkg/cache/task.go, pkg/cache/task_test.go, pkg/common/events/states.go, pkg/common/si_helper.go, pkg/common/si_helper_test.go, pkg/shim/scheduler_test.go
improve `RemoveApplication()` and `TestRemoveApplication()`
=> [YUNIKORN-268] When deleting a deployment the application is not deleted from the shim cache

scripts/run-e2e-tests.sh, test/e2e/README.md, test/e2e/app/app_suite_test.go, test/e2e/app/app_test.go, test/e2e/ci/ci_test.go, test/e2e/framework/helpers/application_utils.go, test/e2e/testdata/application.yaml, test/e2e/testdata/application_error.yaml
Cause the bug of [Yunikorn-314](https://issues.apache.org/jira/browse/YUNIKORN-314)
It will fail in verifying the queue name.
Should wait for Yunikorn-314 be fixed.
=> [YUNIKORN-294] Add e2e test to verify app CRD

go.mod, go.sum
vbom.ml is an indirect dependency which seems to cause issues while
resolving as an import. The project has recently removed the vanity import
for the full github reference.
Even the latest versions of kubernetes seem to rely on this import.
=> [YUNIKORN-389] Replace vanity import for vbom.ml

deployments/admission-controllers/scheduler/templates/server.yaml.template, pkg/plugin/admissioncontrollers/webhook/webhook.go
Changed the admission controller port nr to 9089.
Tested with both Minikube and Docker Desktop
=> [YUNIKORN-380] Deploying YUNIKORN 0.9 RC2 on Minikube 1.3.1 results in port conflict

pkg/cache/application.go, pkg/cache/placeholder_manager.go, pkg/cache/placeholder_manager_test.go, pkg/cache/task.go
Clean up all placeholder pod and task.
Please review @yangwwei 
Thanks.
=> [YUNIKORN-459]Implement the placeholder cleanup in PlaceholderManager

.travis.yml
Build changes to move to go 1.15 tool set.
Upgrade golangci-lint to the latest (also go 1.15 based)
=> [YUNIKORN-369] Set the default go version to 1.15

pkg/cache/placeholder_manager.go, pkg/cache/placeholder_manager_test.go
Run a goroutine to delete orphan placeholders every 5 seconds.
Please review @yangwwei .
Thanks.
=> [YUNIKORN-469]Implement recycling service in PlaceholderManager that cleans up orphan placeholders

go.mod, go.sum
Update go mod files after upgrading the dependent version of scheduler-interface and core to v0.10.0
=> [YUNIKORN-597] update go mod files for v0.10.0 release

pkg/cache/task.go, pkg/cache/task_test.go, pkg/common/events/recorder.go
Publish the pod level event message to pods, which will be gang scheduled.
Indicate user those pods will be gang scheduled.
* https://issues.apache.org/jira/browse/YUNIKORN-628
Unit test had been added to test the the `GetRecorder()` and `Eventf()` called time.
=> [YUNIKORN-628]Publish a pod event to indicate the task is being gang scheduling

deployments/image/configmap/Dockerfile, pkg/appmgmt/general/general.go, pkg/appmgmt/general/general_test.go, pkg/common/constants/constants.go, pkg/common/utils/utils.go, pkg/common/utils/utils_test.go, pkg/conf/schedulerconf.go, pkg/conf/schedulerconf_test.go
Improved methodology for determining k8s user. This PR helps to retrieve user identity from predefined labels
Remaining tasks are recorded under https://issues.apache.org/jira/browse/YUNIKORN-649
https://issues.apache.org/jira/browse/YUNIKORN-650
By passing a Label in the Pod/Deployment that indicates a user. 
https://issues.apache.org/jira/browse/YUNIKORN-651
=> [YUNIKORN-650] Retrieve user identity from predefined labels

pkg/appmgmt/general/general.go, pkg/cache/application.go, pkg/cache/application_events.go, pkg/cache/application_test.go, pkg/cache/task.go, pkg/callback/scheduler_callback.go, pkg/client/apifactory_mock.go, pkg/client/interfaces.go, pkg/client/kubeclient.go, pkg/client/kubeclient_mock.go, pkg/common/constants/constants.go, pkg/common/utils/utils.go, pkg/shim/scheduler.go
When an application fails or is rejected by the scheduler, the pods currently stay in pending forever without visibility on what happened to them. This PR propagates the scheduling error or failure to the pods so that the user will be able to see the reason of failure. If third-party operators (e.g. Spark K8s Operator) are used, they can also react according to the pod status change and update the status of the corresponding CRD and possibly retry. Core side changes are in https://github.com/apache/incubator-yunikorn-core/pull/271
https://issues.apache.org/jira/browse/YUNIKORN-657
Added unit tests to cover this change. When running in a cluster, tested that scheduling failures will be reflected on the pods:
For example, if an application is rejected, its pods will be marked as failed and …
=> [YUNIKORN-657] Expose application failure reasons

pkg/common/utils/gang_utils.go, pkg/common/utils/gang_utils_test.go
It isn't an error that schedulingPolicyParameters is undefined.
It should return nil.
https://issues.apache.org/jira/browse/YUNIKORN-590
I add TestGetPlaceholderTimeoutParam in gang_utils_test.go to observe its behavior.
=> [YUNIKORN-590] GetPlaceholderTimeoutParam: undefined param is not an error

pkg/cache/application.go, pkg/client/kubeclient.go
Pod status update may occasionally fail because the pod could have been modified since the last Get operation. This PR changed the status update logic to get the latest version before update. Also retry a few times if the update fails.
* https://issues.apache.org/jira/browse/YUNIKORN-657
Ran a deployment with this patch for two weeks and haven't found another instance where the update didn't work
=> YUNIKORN-657: Get the latest copy of a pod before attempting status update. Retry in case of failure

deployments/image/configmap/Dockerfile
The admission controller failed to start because we failed to generate the certificate.
The error related the cert geneeration is the following one:
`no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`
Upgrading kubectl to 1.19 will solve the issue for 1.19 version.
https://issues.apache.org/jira/browse/YUNIKORN-674
- running the e2e tests for both K8s 1.19 and for older versions as well
- manual tests
=> [YUNIKORN-674] Fixed admission controller for K8s v. 1.19

deployments/scheduler/scheduler.yaml, deployments/scheduler/yunikorn-rbac.yaml
yunikorn-rbac.yaml creates a ClusterRoleBinding for account: yunikorn-admin. However, scheduler.yaml uses `default` account to query cluster so it encounters permission issue even if we have applied yunikorn-rbac.yaml according to docs.  
https://issues.apache.org/jira/browse/YUNIKORN-765
test it manually
=> [YUNIKORN-765] the RBAC role created by yunikorn-rbac.yaml is not used by scheduler.yaml

go.mod, go.sum, pkg/common/constants/constants.go, pkg/common/si_helper.go, pkg/common/si_helper_test.go
Add new `allocationTags` named `yunikorn.apache.org/ignoreUnschedulableNodes`.
if the pod  belongs to DaemonSet, the `yunikorn.apache.org/ignoreUnschedulableNodes` should be `true`.
https://issues.apache.org/jira/browse/YUNIKORN-757
=> [YUNIKORN-757] Discover daemonset pods and tag with ignoreUnschedulableNodes attributes

pkg/cache/external/scheduler_cache.go, pkg/cache/external/scheduler_cache_test.go
```go
n, ok := cache.nodesMap[pod.Spec.NodeName]
if !ok {
return fmt.Errorf("node %v is not found", pod.Spec.NodeName)
}
if err := n.RemovePod(pod); err != nil {
return err
}
```
It can causes DEBUG log("node  is not found") if node name is an empty string. For example: the pod status is updated (according to outstanding requests) before it is assumed to be run on a node.
https://issues.apache.org/jira/browse/YUNIKORN-770
`TestRemovePodWithoutNodeName`
=> [YUNIKORN-770] Remove unnecessary DEBUG log while removing a pod from the cache

Makefile
The license check run as part of the PR workflow always passes when run on linux.
The recursive grep redirect to a variable does not work.
https://issues.apache.org/jira/browse/YUNIKORN-771
NA
=> [YUNIKORN-771] make license-check fix for linux

pkg/common/events/recorder.go, pkg/conf/schedulerconf.go, pkg/shim/scheduler.go
Avoid data race which R/W in same time.
Add getting TestMode in config object with R lock
https://issues.apache.org/jira/browse/YUNIKORN-805
make test with Makefile
=> [YUNIKORN-805] Fix race condition on the TestMode flag

pkg/shim/scheduler.go
Context:
YuniKorn scheduler restart failed multiple times affecting our production workload. 
During recovery no nodes are added to the scheduler cache.
Potential Causes: 
YuniKorn scheduler restart timeout is set very long (> 6min every time) while K8s API server responds with exponential backoffs. Failed scheduler container does not terminate.
Current Solutions: 
Reduce scheduler recovery timeout and terminate failed scheduler container
https://issues.apache.org/jira/browse/YUNIKORN-703
=> [YUNIKORN-703] Reduce scheduler recovery timeout and terminate failed container

pkg/cache/node.go, pkg/cache/node_test.go, pkg/cache/nodes.go, pkg/common/constants/constants.go
Node labels need to be passed into "YuniKorn Core" via "YuniKorn Scheduler Interface" (YK SI) as node attributes. It then can be considered during node sorting.
In particular, to keep the protobuf value type of node attributes still string, we plan to marshal node labels (map[string]string) into a JSON string before passing to YK SI.
https://issues.apache.org/jira/browse/YUNIKORN-858
=> [YUNIKORN-858] Pass node labels as node attributes for node sorting

pkg/appmgmt/interfaces/amprotocol.go, pkg/cache/amprotocol_mock.go, pkg/cache/application.go, pkg/cache/context.go, pkg/cache/context_test.go, pkg/callback/scheduler_callback.go, pkg/shim/scheduler_test.go
The shim context RemoveApplicationInternal and RemoveTask should not return an error if the application or task is not found.
I set the return value of RemoveApplicationInternal and RemoveTask to nil, so that no matter whether the task or application to be deleted exists or not, it will not return error.
Modify TestRemoveApplicationInternal and TestRemoveTask in context.go as expected.
(https://issues.apache.org/jira/browse/YUNIKORN-1101)
use "make test" command
=> [YUNIKORN-1101] idempotent remove application and remove task in context

pkg/common/resource.go, pkg/common/resource_test.go
https://github.com/apache/yunikorn-k8shim/blob/a118ba6c4d84804e2a407f9d91196ece4690cf09/pkg/common/resource.go#L61-L63
this code seems to have a bug. When I define resource like this:
request:
nvidia.com/gpu: 1
limit:
nvidia.com/gpu: 1
this is considered as QoS best effort and returned with just
Resources:
pod:1
but I think this is a valid configuration that a pod only specifies GPU resource without memory or CPU. It seems this is the K8s upstream code: qos.GetPodQOS() causes this..
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
=> [YUNIKORN-2271] Incorrect handling of GPU only resources

deployments/examples/README.md, deployments/examples/preemption/README.md, deployments/examples/preemption/high-priority-job.yaml, deployments/examples/preemption/low-priority-job-outside-fence.yaml, deployments/examples/preemption/low-priority-job.yaml, deployments/examples/preemption/normal-priority-job-with-9999-priority-class.yaml, deployments/examples/preemption/normal-priority-job.yaml, deployments/examples/preemption/yunikorn-configs.yaml
Add an immediately usable example to reduce the learning curve for users.
The example shows how to config priority queue and demonstrates below behaviors of preemption:
1. A task cannot preempt tasks outside its preemption fence.
2. Preemption is aiming to ensure that the queue's resource usage reaches at least the guaranteed amount of resources.
3. Preemption can never leave a queue lower than its guaranteed capacity.
NA
https://issues.apache.org/jira/browse/YUNIKORN-2131
Follow the example steps in yunikorn-k8shim/deployments/examples/preemption/README.md
NA
NA
=> [YUNIKORN-2131] Add ready-to-use example for peemption
