apache/yunikorn-k8shim

Makefile, deployments/scheduler/scheduler-load.yaml
Hi, 
This pr is for solving the problem addressed in [https://github.com/cloudera/yunikorn-core/issues/18](url).
Thanks.
=> Adding CGO_ENABLED option to fix failed docker build

deployments/examples/README.md
Fix for issues raised in the placement rule pr.
=> Cleanup of the README: consistent capitalisation

Makefile
- make (no options) triggers build
- make clean: simple clean of local files
- make test: build and run the defined tests
- make build: build the binaries
- make image: build the binaries and the docker images
=> Makefile consistency changes

helm-charts/yunikorn/templates/configmap.yaml, helm-charts/yunikorn/templates/service.yaml, helm-charts/yunikorn/values.yaml
this PR does following things
- add configmap to the helm chart, so we don't need to create it manually
- make sure all label app value is "yunikorn"
=> Add configmap in helm chart to further simplify the deployment

pkg/conf/schedulerconf.go, pkg/conf/schedulerconf_test.go, pkg/dispatcher/dispatcher.go
=> Make capacity of dispatcher's event channel configurable

pkg/common/resource.go, pkg/common/resource_test.go
Pod that do not have a resource request are not scheduled by the core scheduler. They stay in a pending state. This was logged as an issue against the core: cloudera/yunikorn-core#54 The problem is that scheduling requires a non nil, not zero, resource request.
This PR implements option 2: set a small resource request if the pod is best effort.
This will be reversed when the core has full support for option 1.
=> Support for pod with QOS BestEffort (no resources)

pkg/client/kubeclient.go, pkg/conf/schedulerconf.go, pkg/conf/schedulerconf_test.go
=> Make QPS/Burst configurable for kubeclient

pkg/cache/application.go, pkg/cache/application_events.go, pkg/cache/application_test.go, pkg/cache/context_test.go, pkg/cache/task.go, pkg/common/events/events.go, pkg/common/events/states.go, pkg/shim/scheduler.go, pkg/shim/scheduler_test.go
This is a replacement for https://github.com/cloudera/yunikorn-k8shim/pull/56. Refined the scheduling logic to reduce the num of events generated in each scheduler interval.
=> Perf improvement: refine scheduling logic in shim to reduce num of events

pkg/conf/schedulerconf.go, pkg/conf/schedulerconf_test.go, pkg/plugin/predicates/predicator_test.go, pkg/plugin/predicates/predictor.go
This is initial PR for #62 .
@yangwwei @wilfred-s , please help to review. Thanks.
=> Support configuring predicates via command-line flag

deployments/admission-controllers/schedulername-mutation/server.yaml.template, landmark/docker_images.yaml
Update docke image file for admission control changes
=> Update docke image file for admission control

pkg/cache/context.go, pkg/cache/context_test.go, pkg/cache/external/scheduler_cache.go, pkg/cache/task.go, pkg/plugin/predicates/predictor.go, pkg/shim/scheduler_mock.go
this PR explicitly calls assumeVolume/bindVolume/forgetVolume in the shim.
=> Fix PV/PVC issue

Makefile, pkg/cache/context_recovery.go, pkg/common/resource.go
1. when there is no nodes in the cluster, recovery timesout
2. support KUBECONFIG environment variable for local mode
=> Recovery times out if the cluster initially has no nodes

pkg/appmgmt/general/general.go, pkg/appmgmt/general/general_test.go
this fixes https://github.com/apache/incubator-yunikorn-core/issues/90
=> [YUNIKORN-11] release pod resources from the scheduler when its status is completed

.asf.yaml, Makefile, README.md, deployments/examples/README.md, docs/design/predicates.md, docs/how-to-contribute.md
Updating the contribution guide to remove the last references to Cloudera.
Adding a new .asf.yaml file to turn off github issues.
=> [YUNIKORN-5]Change the contribution guide and add .asf.yaml

pkg/log/logger.go
Zap logging requires an encoder to be set Duration and Time.
Duration encoder was not set causing a panic.
Cleanup of the init code of the logger.
=> [YUNIKORN-64] fix zap encoder config

helm-charts/yunikorn/templates/cleanup.yaml, helm-charts/yunikorn/templates/configmap.yaml, helm-charts/yunikorn/templates/rbac.yaml, helm-charts/yunikorn/values.yaml
Please refer to issue: https://issues.apache.org/jira/browse/YUNIKORN-36
=> [YUNIKORN-36] Cleanup leaked resources when deleting the helm chart

deployments/examples/README.md, deployments/examples/tfjob/tf-job-mnist.yaml
Add a tfjob example for yunikorn.
=> [YUNIKORN-171] Add example and document about how to run kubeflow with yunikorn

landmark/docker_images.yaml
These changes should not have been made for this file.
=> [YUNIKORN-267] revert landmark changes

.travis.yml, deployments/admission-controllers/scheduler/templates/server.yaml.template, scripts/create_k8s_cluster.sh, scripts/run-e2e-tests.sh
Ensure e2e tests are running against the latest codebase.
=> [YUNIKORN-246] Travis CI: Build the docker image locally for e2e tests.

pkg/cache/application_test.go, scripts/run-e2e-tests.sh
remove installCRD option during helm install.
=> [YUNIKORN-349] Remove installCRD option during helm install for e2e test

go.mod, go.sum, pkg/cache/application.go, pkg/cache/application_events.go, pkg/cache/application_test.go, pkg/cache/context.go, pkg/cache/context_test.go, pkg/cache/task.go, pkg/callback/scheduler_callback.go, pkg/common/events/events.go, pkg/common/si_helper.go
Delete pod when receive `ReleaseAllocation` response, and delete application from context when receive `UpdatedApplication` response.
Please review @yangwwei 
Thanks.
=> [YUNIKORN-478]Handle app completion at the shim side

pkg/appmgmt/general/general.go
=> [YUNIKORN-565] log placeholderTimeout not defined at DEBUG level

pkg/cache/placeholder_manager.go, pkg/cache/placeholder_manager_test.go
Fix the initialisation of the PlaceholderManager structure to init the
channel and orphanPods map (renamed).
Fix the tests to call NewPlaceholderManager to not init the structure in
the test code and thus hiding init issues.
The stop channel is never closed and should be reused. We should not
create a new channel in the Start but in the New call. Fix up the Stop
checks to not use one long 5 second timeout but check every 100ms. This
change speeds up the test (down to 0.2s from 8s) and the shutdown of the
whole shim.
=> [YUNIKORN-600] PlaceholderManager structure init

.github/PULL_REQUEST_TEMPLATE
Add Pull-request-template for yunikorn-k8shim
https://issues.apache.org/jira/browse/YUNIKORN-608
https://github.com/apache/incubator-yunikorn-k8shim/pull/250/checks?check_run_id=2208144163
=> [YUNIKORN-608] Pull-request-template for yunikorn-k8shim

pkg/cache/context.go
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
when hot-refresh is enabled, user cannot use rest api to update the configuration, should set enableconfighotrefresh to false , the message tell user to set true.
[ * ] - Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
https://issues.apache.org/jira/browse/YUNIKORN-644
=> [YUNIKORN-644] Message is wrong when use rest api to edit config.

deployments/yunikorn-application/application-definition.yaml
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
Use apiversion:v1
=> [YUNIKORN-622] Replace deprecated apiVersion v1beta1

pkg/cache/node.go, pkg/cache/node_test.go
Add NodeID to log.
Make log message have identity information.
https://issues.apache.org/jira/browse/YUNIKORN-663
use go test in incubator-yunikorn-k8shim/pkg/cache
=> [YUNIKORN-663] Improve log messages in node.go

pkg/client/kubeclient_mock.go
This PR is for reproducing situation of Data Race
https://issues.apache.org/jira/browse/YUNIKORN-673
This PR is for reproducing situation of Data Race.
It should be resolved in build stage.
See more in https://github.com/apache/incubator-yunikorn-k8shim/pull/264/checks?check_run_id=2607329247
=> [YUNIKORN-673] Data race in kubeclient_mock

pkg/cache/application_events_test.go
Check code coverage and effect of application_events_test.go
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-383
Use make test to veiw the result and coverage.
=> [YUNIKORN-383] Improve code coverage for application_events.go

deployments/examples/predicates/pod-with-toleration.yaml
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
I test predicates examples、volume examples and add pod-with-toleration.yaml.
test predicates.
=> YUNIKORN-672. Verify predicates functions for K8s 1.19

go.mod, go.sum
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
https://issues.apache.org/jira/browse/YUNIKORN-733
=> [YUNIKORN-733] Update shim and core dependencies on master branch

.github/workflows/main.yml
Added 1.20 to the e2e test support matrix
* https://issues.apache.org/jira/browse/YUNIKORN-707
=> [YUNIKORN-707] Add 1.20 to the e2e test support matrix

test/e2e/app/app_test.go, test/e2e/basic_scheduling/basic_scheduling_test.go, test/e2e/framework/configmanager/constants.go, test/e2e/framework/helpers/yunikorn/rest_api_utils.go, test/e2e/predicates/predicates_test.go, test/e2e/queue_quota_mgmt/queue_quota_mgmt_suite_test.go, test/e2e/queue_quota_mgmt/queue_quota_mgmt_test.go, test/e2e/state_aware_app_scheduling/drip_feed_schedule_test.go, test/e2e/state_aware_app_scheduling/fallback_test.go
Call and check the yunikorn HealthCheck API in all kind of e2e test.
https://issues.apache.org/jira/browse/YUNIKORN-744
=> [YUNIKORN-744]Call healthcheck REST API in e2e tests

pkg/cache/placeholder_manager.go
The busy loop can be refactor by select timeout.
https://issues.apache.org/jira/browse/YUNIKORN-806
rely on existent test
=> [YUNIKORN-806] Refactor busy loop of PlaceholderManager#start

pkg/common/utils/utils.go
Fix log level from info to debug
https://issues.apache.org/jira/browse/YUNIKORN-801
=> [YUNIKORN-801] Empty user label log should be DEBUG level

pkg/cache/placeholder_manager.go
Solve the data race from UT
https://issues.apache.org/jira/browse/YUNIKORN-841
=> [YUNIKORN-841] Data race in TestResumingStateTransitions()

DISCLAIMER, NOTICE
Add NOTICE and DISCLAIMER files to repos
https://issues.apache.org/jira/browse/YUNIKORN-789
=> [YUNIKORN-789] Add NOTICE and DISCLAIMER files to all yunikorn repos

deployments/examples/README.md
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-934
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-934
=> [YUNIKORN-934] Correct the link in deployments/examples/Readme

.github/workflows/main.yml, scripts/run-e2e-tests.sh
e2e tests are failing. Need to use Go version 1.16.
https://issues.apache.org/jira/browse/YUNIKORN-939
=> [YUNIKORN-939] shim e2e tests fail on go 1.15

pkg/appmgmt/appmgmt_recovery.go, pkg/appmgmt/general/general.go, pkg/cache/application.go, pkg/shim/scheduler.go
Added a few new log messages for the case when there is no outstanding requests. 
Also added a log message for the recovery part, to check if we got an answer from the api server or not
https://issues.apache.org/jira/browse/YUNIKORN-932
=> [YUNIKORN-932] Added some extra log message

go.mod, go.sum
Updated core dependency to the latest master commit. Once merged, I'll cherry-pick this commit into branch-0.12
https://issues.apache.org/jira/browse/YUNIKORN-895
=> [YUNIKORN-895] Updated core dependency to the latest master commit

go.mod, go.sum
Updated core and SI to v0.12.0 tag in branch-0.12
https://issues.apache.org/jira/browse/YUNIKORN-896
=> [YUNIKORN-896] Updated core and SI to v0.12.0 tag

deployments/examples/README.md
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-973
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-973
no need
=> [YUNIKORN-973] Correct the link in master/deployments/examples

deployments/examples/tfjob/Dockerfile, deployments/examples/tfjob/README.md, deployments/examples/tfjob/dist_mnist.py
Add dockerfile and distributed MNIST example 
related to : https://github.com/apache/incubator-yunikorn-site/pull/96
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-953)
=> [YUNIKORN-953] Investigate of kubeflow/training-operator

test/e2e/predicates/predicates_suite_test.go, test/e2e/state_aware_app_scheduling/drip_feed_schedule_test.go
Remove outdated comments in predicates_suite_test.go and drip_feed_schedule_test.go
https://issues.apache.org/jira/browse/YUNIKORN-987
=> [YUNIKORN-987] remove references to Cloudera jiras

Makefile
Adds the SHA sums for the various code components to the admission controller image similarly to how it is currently done for the scheduler image.
https://issues.apache.org/jira/browse/YUNIKORN-1009
=> [YUNIKORN-1009] Add git sha as label to admission controller image

.github/workflows/main.yml
Updates e2e workflow to run tests in plugin mode as well as standard mode.
https://issues.apache.org/jira/browse/YUNIKORN-1058
PR pre-commit should run.
=> [YUNIKORN-1058] Update e2e tests to exercise plugin mode as well

go.mod, pkg/cache/application_graphviz_test.go, pkg/cache/node_graphviz_test.go, pkg/cache/task_graphviz_test.go, pkg/plugin/admissioncontrollers/webhook/admission_controller.go, pkg/shim/scheduler_graphviz_test.go, test/e2e/framework/helpers/common/utils.go
Go's ioutil package to be deprecated in 1.16
change ioutil to io or os
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1027
=> [YUNIKORN-1027] Go: deprecation of io/ioutil

test/e2e/framework/helpers/k8s/k8s_utils.go, test/e2e/framework/helpers/yunikorn/yk_utils.go, test/e2e/node_resources/node_resources_suite_test.go, test/e2e/node_resources/node_resources_test.go
Added test suites to verify the node resources.
https://issues.apache.org/jira/browse/YUNIKORN-1537
=> [YUNIKORN-1537] Add node resources test suites

pkg/cache/task.go
The QuatoApproved state has been removed in the previous issue. There was an omission, so this PR removes that.
N/A
[YUNIKORN-2222](https://issues.apache.org/jira/browse/YUNIKORN-2222/)
Unit test and e2e test.
N/A
N/A
=> [YUNIKORN-2222] Remove unused state
